CC = m68k-atari-mint-gcc

CFLAGS = -Os -I/usr/m68k-atari-mint/include/SDL -mcpu=5475 -I./WRAPPER
LDFLAGS = -s -lSDL -lgem
DEFINES = -Wall -DUNCAPPED
DEFINES += -DSAVE
OUTPUT = kill_cold.tos

SOURCES = main.c WRAPPER/PC_SDL12.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${DEFINES} ${LDFLAGS}
	
clean:
	rm *.o
	rm ${OUTPUT}
