CC = kos-cc
SH_DIRECTORY = /opt/toolchains/dc/sh-elf/bin/

CFLAGS = -Os -Wall -DDREAMCAST -I$(KOS_BASE)/addons/include/SDL -I$(KOS_BASE)/addons/include
LDFLAGS = -lSDL -lmp3 -ltremor -lmp3 -lm
DEFINES = -DDEBUG -DSOUND_ENABLED -DJOYSTICK
DEFINES += -DSAVE -DDREAMCAST
OUTPUT = killminds_dreamcast

SOURCES = main.c WRAPPER/DREAMCAST.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT}.elf ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES}
	
clean:
	rm *.o
	rm ${OUTPUT}
	
scramble:
	${SH_DIRECTORY}sh-elf-objcopy -R .stack -O binary ${OUTPUT}.elf ${OUTPUT}.bin
	
