CC = i586-mingw32msvc-gcc

CFLAGS = -Os -I./WRAPPER
LDFLAGS = -lSDL2 -lSDL2_mixer -mwindows -lmingw32
DEFINES = -Wall -DRECENT_RENDER -DSAVE -DSOUND_ENABLED
DEFINES += -DSAVE
OUTPUT = Killminds.exe

SOURCES = main.c WRAPPER/PC_SDL2.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm *.o
	rm ${OUTPUT}
