CC = nspire-gcc

CFLAGS = -Os -Wall -Werror -I./WRAPPER -I.
LDFLAGS = -flto
DEFINES = -DSAVE
OUTPUT = killminds

SOURCES = main.c WRAPPER/NSPIRE.c n2DLib.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm *.o
	rm ${OUTPUT}
