        
short rand_a_b(short a, short b);
void load_game_memory();
void InitializeGame();
void GameLoop();
void Show_platforme_gauche_0();
void Show_platforme_gauche_1();
void Show_platforme_droite_0();
void Show_platforme_droite_1();
void Show_GameOver();
void Show_score();
void Add_score();
void Show_helices();
void Init_Audio();
void play_smack();
void play_switch();
void Reset_game();
void Gameplay();
void Collisions();
void Platforms_manage();
void Show_Bottom_back();
void Show_Clouds();
void Show_Hammer();
void Show_Player();
void Move_player();
void A_button();
void Trigger_Death(); 
