CC = gcc

CFLAGS = -I/usr/include/ -I/usr/include/allegro5 -L/usr/lib -Os -I./WRAPPER
LDFLAGS = -lallegro -lallegro_image -lallegro_audio -lallegro_acodec
DEFINES += -DIMAGE_CODEC_ENABLED
DEFINES += -DSOUND_ENABLED
DEFINES += -DRECENT_RENDER
OUTPUT = heli_alleg5

SOURCES = main.c WRAPPER/PC_ALLEG5.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm *.o
	rm ${OUTPUT}
