CC = arm-linux-androideabi-gcc

CFLAGS = -Os -I./WRAPPER
LDFLAGS = -lSDL2 -lSDL2_image -lpng -lwebp -lz -lm -ljpeg
DEFINES = -DDEBUG
DEFINES += -DIMAGE_CODEC_ENABLED
DEFINES += -DRECENT_RENDER
OUTPUT = example

SOURCES = main.c WRAPPER/PC_SDL2.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm *.o
	rm ${OUTPUT}
