CC = gcc

CFLAGS = -Os -I./WRAPPER
LDFLAGS = `allegro-config --libs`
DEFINES = -DDEBUG 
DEFINES += -DSOUND_ENABLED
OUTPUT = example

SOURCES = main.c WRAPPER/PC_ALLEG4.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm *.o
	rm ${OUTPUT}
